<?php

return [
    'info' => ['tr' => 'Bilgi', 'en' => 'Information'],
    'shield-check' => ['tr' => 'Güvenlik', 'en' => 'Security'],
    'badge-check' => ['tr' => 'Doğrulama', 'en' => 'Verification'],
    'user-round' => ['tr' => 'Profil', 'en' => 'Profile'],
    'users' => ['tr' => 'Ekip', 'en' => 'Team'],
    'users-round' => ['tr' => 'Topluluk', 'en' => 'Community'],
    'id-card' => ['tr' => 'Kimlik', 'en' => 'Identity'],
    'graduation-cap' => ['tr' => 'Eğitim', 'en' => 'Education'],
    'award' => ['tr' => 'Ödül', 'en' => 'Award'],
    'star' => ['tr' => 'Öne çıkan', 'en' => 'Featured'],
    'map-pin' => ['tr' => 'Konum', 'en' => 'Location'],
    'languages' => ['tr' => 'Diller', 'en' => 'Languages'],
    'plane' => ['tr' => 'Seyahat', 'en' => 'Travel'],
    'calendar' => ['tr' => 'Takvim', 'en' => 'Calendar'],
    'calendar-check' => ['tr' => 'Planlama', 'en' => 'Planning'],
    'calendar-clock' => ['tr' => 'Takvim ve zaman', 'en' => 'Schedule'],
    'clock' => ['tr' => 'Zaman', 'en' => 'Time'],
    'briefcase-business' => ['tr' => 'İş ve deneyim', 'en' => 'Work experience'],
    'building' => ['tr' => 'Şirket', 'en' => 'Company'],
    'handshake' => ['tr' => 'İş birliği', 'en' => 'Collaboration'],
    'target' => ['tr' => 'Hedef', 'en' => 'Target'],
    'rocket' => ['tr' => 'Başlangıç ve büyüme', 'en' => 'Launch and growth'],
    'laptop' => ['tr' => 'Bilgisayar', 'en' => 'Computer'],
    'smartphone' => ['tr' => 'Mobil', 'en' => 'Mobile'],
    'code-xml' => ['tr' => 'Kodlama', 'en' => 'Coding'],
    'terminal' => ['tr' => 'Terminal', 'en' => 'Terminal'],
    'server-cog' => ['tr' => 'Sunucu', 'en' => 'Server'],
    'database' => ['tr' => 'Veritabanı', 'en' => 'Database'],
    'cloud' => ['tr' => 'Bulut', 'en' => 'Cloud'],
    'network' => ['tr' => 'Ağ', 'en' => 'Network'],
    'radio-tower' => ['tr' => 'İletişim ağı', 'en' => 'Connectivity'],
    'blocks' => ['tr' => 'Modüller', 'en' => 'Modules'],
    'plug' => ['tr' => 'Entegrasyon', 'en' => 'Integration'],
    'plug-zap' => ['tr' => 'API entegrasyonu', 'en' => 'API integration'],
    'git-pull-request' => ['tr' => 'Sürüm kontrolü', 'en' => 'Version control'],
    'bug' => ['tr' => 'Hata ayıklama', 'en' => 'Debugging'],
    'lock-keyhole' => ['tr' => 'Erişim güvenliği', 'en' => 'Access security'],
    'layout-template' => ['tr' => 'Arayüz tasarımı', 'en' => 'Interface design'],
    'layout-dashboard' => ['tr' => 'Yönetim paneli', 'en' => 'Dashboard'],
    'folder-kanban' => ['tr' => 'Proje yönetimi', 'en' => 'Project management'],
    'folder-check' => ['tr' => 'Tamamlanan proje', 'en' => 'Completed project'],
    'package-search' => ['tr' => 'Ürün ve paket', 'en' => 'Product and package'],
    'shopping-cart' => ['tr' => 'E-ticaret', 'en' => 'E-commerce'],
    'qr-code' => ['tr' => 'QR kod', 'en' => 'QR code'],
    'chart-column' => ['tr' => 'Analiz ve raporlama', 'en' => 'Analytics'],
    'globe-2' => ['tr' => 'Web', 'en' => 'Web', 'render' => 'globe'],
    'mail' => ['tr' => 'E-posta', 'en' => 'Email'],
    'phone' => ['tr' => 'Telefon', 'en' => 'Phone'],
    'message-circle' => ['tr' => 'Mesaj', 'en' => 'Message'],
    'link' => ['tr' => 'Bağlantı', 'en' => 'Link'],
    'file-text' => ['tr' => 'Doküman', 'en' => 'Document'],
    'lightbulb' => ['tr' => 'Fikir', 'en' => 'Idea'],
    'sparkles' => ['tr' => 'Öne çıkan özellik', 'en' => 'Highlighted feature'],
    'milestone' => ['tr' => 'Teknik karar', 'en' => 'Technical decision'],
    'list-restart' => ['tr' => 'Dinamik liste', 'en' => 'Dynamic list'],
    'moon-star' => ['tr' => 'Tema', 'en' => 'Theme'],
    'layout-list' => ['tr' => 'Bölümler', 'en' => 'Sections'],
    'test-tube-diagonal' => ['tr' => 'Test', 'en' => 'Test'],
    'palette' => ['tr' => 'Tasarım', 'en' => 'Design'],
    'wrench' => ['tr' => 'Araçlar', 'en' => 'Tools'],
    'heart' => ['tr' => 'İlgi alanı', 'en' => 'Interest'],
    'circle-check' => ['tr' => 'Tamamlandı', 'en' => 'Completed'],
];
